### PR TITLE
broom::tidy() microbenchmark object would cause error

### PR DESCRIPTION
**Pull request by dongzhuoer**
microbenchmark   1.4-6    2018-10-18 [1] CRAN (R 3.5.1)
broom                    0.5.1    2018-12-05 [1] CRAN (R 3.5.1)

### CODE REVIEW

**Comment by dongzhuoer** [comment]
```
> mb_prom_median <- broom::tidy(mb_prom)[2,]$median
Error in median.default(X[[i]], ...) : need numeric data
In addition: Warning messages:
1: 'tidy.data.frame' is deprecated.
See help("Deprecated")
2: In mean.default(X[[i]], ...) :
  argument is not numeric or logical: returning NA
3: In var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm) :
  Calling var(x) on a factor x is deprecated and will become an error.
  Use something like 'all(duplicated(x)[-1L])' to test for a constant vector.
> mb_prom_median <- summary(mb_prom)$median
> round(420 / mb_prom_median, 4) * 100
[1] 1.48
```

**Comment by dongzhuoer** [comment]
image

The value is roughly equal to that in the current HTML output.

**Comment by dongzhuoer** [comment]
I assign the copyright of this contribution to Malte Grosser and Henning Bumann.

**Comment by henningsway** [comment]
Thanks so much!

**Pull request closed without merging**
