### PR TITLE
Feedback on S4

### PR DESCRIPTION
**Pull request by hadley**

### CODE REVIEW

**Comment by hadley** [comment]
Fixes #200

**Comment by henningsway** [comment]
For some reason a merge was not possible, the main file may have been slightly outdated, before the review.

Anyway we merged your comments into the main branch in https://github.com/Tazinho/Advanced-R-Solutions/commit/e75ba084206ab78a49efb248f511ac4183cc512b and will take a closer look at them very soon.

Thank you for the reviews! :)

**Comment by Tazinho** [comment]
@hadley: thank you for the review. For some reason it seems, that you have worked on an older Rmd version of the S4 chapter. We believe this in worst case you could have overlooked most current solutions for #Method dispatch Q1 & Q2 and #S4 and S3 Q1. Could you pls check these once more?

**Comment by hadley** [comment]
Oh yeah, this is because you switched default branches, and it took me a little while to figure out. I'll take another pass.

**Comment by hadley** [comment]
I am now deeply regretting asking those questions 😭 I have never been very good at puzzling them out and I just don't have enough S4 loaded in my brain. If you really want to check they're correct, I'd suggest tweeting about them and I can retweet. S4 & S3 answer looks good.

**Comment by Tazinho** [comment]
I think that is perfectly fine. We just wanted to make sure you saw everything. And of course it would be annoying if there was an obvious mistake somewhere in the graphics.

**Pull request closed without merging**
