### PR TITLE
Improve code and fix typos of answers for chapters 13 - 16

### PR DESCRIPTION
**Pull request by caijun**
see Files Changed

I assign the copyright of this contribution to Malte Grosser, Henning Bumann, Robert Krzyzanowski and Peter Hurford.

### CODE REVIEW

**Comment by Tazinho** [comment]
Thank you very much for your pull request @caijun !
 
Since this book might be published someday, we needed to include contribution guidelines (similar to the ones in Advanced R). You would do us a great favour, if you read [them](https://github.com/Tazinho/Advanced-R-Solutions/blob/master/CONTRIBUTING.md) and - if you agree - add the needed phrase to the description of your original pull request.

Thanks again,
Malte

**Comment by caijun** [comment]
@Tazinho Thank you for giving solutions for Advance R. I also benefit from your solutions. I am looking forward to see this book to be published. If my contribution would be acknowledged in the book, it's ok for me to give you  the copyright.

Recently I am reading Part IV Performance of Advance R to learn the skills of improving R code performance. Hence, I will continue to contribute to several more chapters (at least chapters 15-16) of proof reading for your solutions.

**Comment by caijun** [comment]
```
> ulapply(cor_list, function(x) identical(x(), cor_v1()))
[1]  TRUE  TRUE  TRUE FALSE

> x <- cor_v1()
> y <- cor_v4()
> x - y
[1] 1.084202e-19
```

I just found I couldn't reproduce this problem every time. It's related to the precision.

**Comment by caijun** [comment]
I just ran the code in pure R script and I understand that you turning evaluation of R code into FALSE to save time for compiling the RMarkdown into  the Book.

However, I felt that hard coding the value of the `mb_median` object was not a wise way. Because one might run this code snippet on his/her own computers.

 I think it's OK to show the code extracting the value but the code behind benchmark plot can use the hard coding values  from your own PC.

**Comment by Tazinho** [comment]
I see. For now I just added a comment in the source code of both answers, so that your comments don't get lost and users won't be confused.

**Comment by Tazinho** [comment]
I merged the rest manually. Thank you a lot for your help!

**Comment by caijun** [comment]
Could you open this PR again so that I can commit the proofing reading for the chapter of Memory?

**Comment by caijun** [comment]
@Tazinho I finished current stage of learning Part IV Performance of Advance R and you can merge this PR and close it. I may contribute other chapters of proof reading if I need to learn other parts of Advance R before this book's publication.

**Comment by Tazinho** [comment]
@caijun Thanks a lot also for this review! This really helps!!!
I clarified some things according to your remarks, so I merged manually, but essentially everything as you inteded.

**Pull request closed without merging**
